sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8ibFSDgJbVmi1Rvmpp
    access-key-secret: ROFvInYGB2OxI7QXKf0O48Idh2F8yO
    bucket-name: studytest20230806
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
    timeout: 10000
  wechat:
    appid: wxa537ac275488939c
    secret: 96bae690c1425a1bec862a9c6eaae292